# Generated by Django 3.2.13 on 2023-02-13 12:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название купона')),
                ('currency', models.CharField(default='rub', max_length=4, verbose_name='Валюта')),
                ('percent_off', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Размер скидки')),
                ('coupon_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='ID купона')),
            ],
            options={
                'verbose_name': 'купон',
                'verbose_name_plural': 'Купоны',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50, verbose_name='Название налога')),
                ('description', models.TextField(verbose_name='Описание налога')),
                ('percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Размер налога')),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='ID такса')),
                ('jurisdiction', models.CharField(max_length=20, verbose_name='Юрисдикция страны')),
            ],
            options={
                'verbose_name': 'налог',
                'verbose_name_plural': 'Налоги',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.discount', verbose_name='Скидки')),
                ('item', models.ManyToManyField(to='api.Item', verbose_name='Предметы')),
                ('tax', models.ManyToManyField(blank=True, to='api.Tax', verbose_name='Налоги')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
