# Generated by Django 3.2.13 on 2023-02-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('rub', 'рубль'), ('usd', 'доллар')], default='rub', max_length=3, verbose_name='Валюта'),
        ),
    ]
