# Generated by Django 3.2.13 on 2023-02-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('rub', '₽'), ('usd', '$')], default='rub', max_length=3, verbose_name='Валюта'),
        ),
    ]
